name: Panutat
favicon: null
layout_spectrum: 0.6266768318600953
typography_spectrum: 0.9804280896205455
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1986163437832147
  lightness: 0.1791561245918274
  saturation: 0.19121934147551656
  rhythmicContrast: 0.5274666482582688
purpose: []
